### PR TITLE
Quick port to Coq 8.13.2 and 8.14.1 and 8.15.1

### LINKED ISSUE #1: Doesn't build with Coq 8.14.1, 8.13.2, 8.12.2, nor 8.11.2
I'd love to use these maps in an experiment of mine, but it doesn't compile with recent enough versions of Coq:
```
File "./Facts.v", line 1752, characters 2-6:
Error:  (in proof not_empty_has_binding): Attempt to save an incomplete proof
```
With 8.11.2 I get
```
File "./Facts.v", line 1829, characters 34-55:
Error: No product even after head-reduction.
```
Are there plans to modernize this library?

### PR DESCRIPTION
**Pull request by xavierleroy**
Also fixed a typo (statement of `partition_avl2`) and added a .gitignore.

Fixes: #1

### CODE REVIEW

**Comment by xavierleroy** [comment]
There was a problem with 8.15.1, which I fixed too.

Any reason for not merging this?  What about an OPAM package?  I could help with that too.

**Comment by xavierleroy** [comment]
Ping?

**Comment by letouzey** [comment]
Hi @xavierleroy. Thanks for the report and the patches. Really sorry for not noticing your Issue earlier, a priori I never got these github notifications (or at least never noticed them). I'll go and check my github settings asap.
Best regards, Pierre

**Comment by xavierleroy** [comment]
No problem, Pierre, maybe I should have @-mentioned you explicitly.  At any rate I'm happy that this MMaps library is about to get a second life, as it contains very nice code, esp. the red-black implementation of finite maps, which is significantly faster than the AVL implementation from the Coq standard library.

**Pull request merged**
